apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-cirros-test-pv-1
  namespace: openshift-adp
spec:
  backupName: backup-cirros-test-pv-all
  labelSelector:
    matchLabels:
      app: cirros-test-pv-1
